// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
)

type User struct {
	ID           int32
	Email        string
	PasswordHash sql.NullString
	GoogleID     sql.NullString
	CreatedAt    sql.NullTime
	AppleID      sql.NullString
	MicrosoftID  sql.NullString
	AvatarUrl    sql.NullString
}
